In [173]:
import pandas as pd

In [174]:
# dataset = pd.read_csv("original_train_data_new.csv")
dataset = pd.read_excel("code_file_1.xlsx")

In [175]:
dataset.head()

,sentences,Explanation
0,"if __name__ == ""__main__"":\n print(""Hello, ...",The code snippet uses a common Python idiom to...
1,"# Suppose this is foo.py.\n\nprint(""before imp...",The `foo.py` script demonstrates the flow of e...
2,python foo.py\n,"\nThe line math = __import__(""math"") is a less..."
3,# It's as if the interpreter inserts this at t...,"Assigning `__name__ = ""__main__""` directly in ..."
4,# Suppose this is in some other main program.\...,The code snippet you've shared is a Python imp...

In [176]:
dataset.columns

Index(['sentences', 'Explanation'], dtype='object')

In [177]:
dataset.shape

(7978, 2)

In [178]:
# def remove_special_characters(text):

#     text = text.replace("`", "")
#     text = text.replace("**", "")
#     text = text.replace("-", "")
#     text = text.replace(">>>","")
#     text = text.replace("#", "")
#     return text
# dataset["description"] = dataset["description"].apply(remove_special_characters)

In [179]:
import re

def remove_special_characters(text):
    # Check if the input is a string
    if isinstance(text, str):
        # Remove backticks, double asterisks, and hyphens
        text = text.replace("`", "")
        text = text.replace("**", "")
        text = text.replace("-", "")
        # Remove any remaining special characters
        text = re.sub(r'[^\w\s]', '', text)
    return text

In [180]:
dataset["Explanation"] = dataset["Explanation"].apply(remove_special_characters)

In [181]:
dataset.head()

,sentences,Explanation
0,"if __name__ == ""__main__"":\n print(""Hello, ...",The code snippet uses a common Python idiom to...
1,"# Suppose this is foo.py.\n\nprint(""before imp...",The foopy script demonstrates the flow of exec...
2,python foo.py\n,\nThe line math __import__math is a less comm...
3,# It's as if the interpreter inserts this at t...,Assigning __name__ __main__ directly in a Pyt...
4,# Suppose this is in some other main program.\...,The code snippet youve shared is a Python impo...

In [182]:
# def remove_newlines(text):
#     cleaned_text = re.sub(r'[\r\n]+', '', text)
#     return cleaned_text

In [183]:
def remove_newlines1(text):
    # Check if the input is a string
    if isinstance(text, str):
        # Remove all occurrences of newline characters
        cleaned_text = text.replace("\n", "").replace("\r", "")
        return cleaned_text
    else:
        return text

In [184]:
dataset["Explanation"] = dataset["Explanation"].apply(remove_newlines1)

In [185]:
dataset.head()

,sentences,Explanation
0,"if __name__ == ""__main__"":\n print(""Hello, ...",The code snippet uses a common Python idiom to...
1,"# Suppose this is foo.py.\n\nprint(""before imp...",The foopy script demonstrates the flow of exec...
2,python foo.py\n,The line math __import__math is a less common...
3,# It's as if the interpreter inserts this at t...,Assigning __name__ __main__ directly in a Pyt...
4,# Suppose this is in some other main program.\...,The code snippet youve shared is a Python impo...

In [186]:
from huggingface_hub import login 
from datasets import Dataset

In [187]:
dataset = Dataset.from_pandas(dataset)
dataset

Dataset({
    features: ['sentences', 'Explanation'],
    num_rows: 7978
})

In [188]:
dataset = dataset.train_test_split(test_size=0.12)

In [189]:
dataset

DatasetDict({
    train: Dataset({
        features: ['sentences', 'Explanation'],
        num_rows: 7020
    })
    test: Dataset({
        features: ['sentences', 'Explanation'],
        num_rows: 958
    })
})

In [190]:
# dataset.to_csv("updated_dataset.csv", index=False)

In [191]:
# ! pip install huggingface_hub

In [192]:
login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [193]:
dataset.push_to_hub("salony/code_explanations_2")
# dataset.push_to_hub("Ankita802/code_explain")

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/8 [00:00<?, ?ba/s]

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

README.md:   0%|          | 0.00/440 [00:00<?, ?B/s]

CommitInfo(commit_url='https://huggingface.co/datasets/salony/code_explanations_2/commit/5070eb12c103149d647356119537a58e0ee9bf3a', commit_message='Upload dataset', commit_description='', oid='5070eb12c103149d647356119537a58e0ee9bf3a', pr_url=None, pr_revision=None, pr_num=None)

In [131]:
import pandas as pd
import torch
from datasets import load_dataset
df=load_dataset("salony/code_explanations_2")

Downloading readme:   0%|          | 0.00/440 [00:00<?, ?B/s]

Downloading data: 100%|██████████| 3.72M/3.72M [00:00<00:00, 4.12MB/s]
Downloading data: 100%|██████████| 155k/155k [00:00<00:00, 476kB/s]

Generating train split:   0%|          | 0/7057 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/295 [00:00<?, ? examples/s]

In [132]:
df

DatasetDict({
    train: Dataset({
        features: ['sentences', 'Explanation'],
        num_rows: 7057
    })
    test: Dataset({
        features: ['sentences', 'Explanation'],
        num_rows: 295
    })
})