In [2]:
! pip install huggingface_hub

Requirement already satisfied: huggingface_hub in c:\users\salony.garg\appdata\local\programs\python\python311\lib\site-packages (0.22.2)
Requirement already satisfied: filelock in c:\users\salony.garg\appdata\local\programs\python\python311\lib\site-packages (from huggingface_hub) (3.13.4)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\salony.garg\appdata\local\programs\python\python311\lib\site-packages (from huggingface_hub) (2024.2.0)
Requirement already satisfied: packaging>=20.9 in c:\users\salony.garg\appdata\local\programs\python\python311\lib\site-packages (from huggingface_hub) (24.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\salony.garg\appdata\local\programs\python\python311\lib\site-packages (from huggingface_hub) (6.0.1)
Requirement already satisfied: requests in c:\users\salony.garg\appdata\local\programs\python\python311\lib\site-packages (from huggingface_hub) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\salony.garg\appdata\local\programs\python\python311\lib\site-packages (from huggingface_hub) (4.66.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\salony.garg\appdata\local\programs\python\python311\lib\site-packages (from huggingface_hub) (4.11.0)
Requirement already satisfied: colorama in c:\users\salony.garg\appdata\local\programs\python\python311\lib\site-packages (from tqdm>=4.42.1->huggingface_hub) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\salony.garg\appdata\local\programs\python\python311\lib\site-packages (from requests->huggingface_hub) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\salony.garg\appdata\local\programs\python\python311\lib\site-packages (from requests->huggingface_hub) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\salony.garg\appdata\local\programs\python\python311\lib\site-packages (from requests->huggingface_hub) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\salony.garg\appdata\local\programs\python\python311\lib\site-packages (from requests->huggingface_hub) (2024.2.2)

Day 1: Learning

In [16]:
from huggingface_hub import login 
from datasets import Dataset

In [21]:
login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [1]:
import pandas as pd 

data = pd.read_excel('code_new.xlsx')
data

,sentences,Explanation
0,import requests\nimport re\n\ndef crawl_websit...,The provided Python script defines a function ...
1,"[x*x for x in [1, 2, 3, 5, 8, 13]]",The Python list comprehension [x*x for x in [1...
2,def remove_duplicates(string): \n result = ...,The provided Python function remove_duplicates...
3,def generate_random_divisible_number():\n i...,The provided Python function generate_random_d...
4,def third_largest(lst):\n if len(lst) < 3:\...,The provided Python function third_largest aim...
...,...,...
1897,import sqlite3\n\nconn = sqlite3.connect(':mem...,This script demonstrates how to create an SQLi...
1898,import pandas as pd\nimport numpy as np\n\nimp...,This script uses linear regression to predict ...
1899,# Convert list of strings into a single string...,The `list_to_string` function transforms a lis...
1900,def reverse_string(text): \n # Convert stri...,The `reverse_string` function takes a string `...
1901,from sklearn.decomposition import PCA\npca = P...,These lines of code perform Principal Componen...

In [3]:
data.isnull().sum()

sentences      4
Explanation    7
dtype: int64

In [4]:
# data = data.iloc[0:2499,0:2]
data=data.dropna()

In [5]:
data.isnull().sum()

sentences      0
Explanation    0
dtype: int64

In [6]:
data.head()

,sentences,Explanation
0,import requests\nimport re\n\ndef crawl_websit...,The provided Python script defines a function ...
1,"[x*x for x in [1, 2, 3, 5, 8, 13]]",The Python list comprehension [x*x for x in [1...
2,def remove_duplicates(string): \n result = ...,The provided Python function remove_duplicates...
3,def generate_random_divisible_number():\n i...,The provided Python function generate_random_d...
4,def third_largest(lst):\n if len(lst) < 3:\...,The provided Python function third_largest aim...

In [30]:
data.isnull().sum()

sentences        4
Explanation    102
dtype: int64

In [31]:
data.dropna(inplace=True)

In [32]:
data.isnull().sum()

sentences      0
Explanation    0
dtype: int64

In [7]:
data

,sentences,Explanation
0,import requests\nimport re\n\ndef crawl_websit...,The provided Python script defines a function ...
1,"[x*x for x in [1, 2, 3, 5, 8, 13]]",The Python list comprehension [x*x for x in [1...
2,def remove_duplicates(string): \n result = ...,The provided Python function remove_duplicates...
3,def generate_random_divisible_number():\n i...,The provided Python function generate_random_d...
4,def third_largest(lst):\n if len(lst) < 3:\...,The provided Python function third_largest aim...
...,...,...
1897,import sqlite3\n\nconn = sqlite3.connect(':mem...,This script demonstrates how to create an SQLi...
1898,import pandas as pd\nimport numpy as np\n\nimp...,This script uses linear regression to predict ...
1899,# Convert list of strings into a single string...,The `list_to_string` function transforms a lis...
1900,def reverse_string(text): \n # Convert stri...,The `reverse_string` function takes a string `...
1901,from sklearn.decomposition import PCA\npca = P...,These lines of code perform Principal Componen...

In [23]:
import pandas as pd

# Load the Excel files into Pandas DataFrames
file1 = pd.read_excel('linkss 1.xlsx')
file2 = pd.read_excel('code_new.xlsx')

# Merge the DataFrames
merged_data = pd.concat([file1, file2], ignore_index=True)

# Write the merged data to a new Excel file
data=merged_data.to_excel('code_file.xlsx', index=False)

In [24]:
# from datasets import load_dataset, concatenate_datasets

# # Load the existing dataset
# dataset = load_dataset('salony/code_explanations')

# # Load the new data (assuming it's also in the same format)
# new_data = load_dataset(dataset)

# # Concatenate the new data with the existing dataset
# updated_dataset = concatenate_datasets([dataset, new_data])

# # Save the updated dataset

# updated_dataset.push_to_hub("salony/code_explanations")

In [17]:
dataset = Dataset.from_pandas(file2)
dataset

Dataset({
    features: ['sentences', 'Explanation'],
    num_rows: 1902
})

In [34]:
dataset=dataset.remove_columns(["__index_level_0__"])

In [18]:
dataset = dataset.train_test_split(test_size=0.2)

In [19]:
dataset

DatasetDict({
    train: Dataset({
        features: ['sentences', 'Explanation'],
        num_rows: 1521
    })
    test: Dataset({
        features: ['sentences', 'Explanation'],
        num_rows: 381
    })
})

In [37]:
dataset.push_to_hub("salony/code_explanations_2")

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/5 [00:00<?, ?ba/s]

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/2 [00:00<?, ?ba/s]

CommitInfo(commit_url='https://huggingface.co/datasets/salony/code_explanations/commit/fa80d9517bd2c139f830a6180544a885a42e43f6', commit_message='Upload dataset', commit_description='', oid='fa80d9517bd2c139f830a6180544a885a42e43f6', pr_url=None, pr_revision=None, pr_num=None)